### ISSUE TITLE
Fix "Runs via SteamPlay" for Linux client

### ISSUE THREAD

**Issue by AccountOneOff** [airforsteam/Air-for-Steam#200] opened 2018-08-28 00:46 UTC
With the addition of SteamPlay brings along a new dialog. Air for Steam doesn't support this currently so the text gets in the way of the list view. 

What it looks like with Air:

![screenshot from 2018-08-27 16-11-00](https://user-images.githubusercontent.com/15083452/44693651-42210080-aa1e-11e8-9636-200fe32fb64c.png)

Default skin:

![screenshot from 2018-08-27 17-26-25](https://user-images.githubusercontent.com/15083452/44693674-5c5ade80-aa1e-11e8-9bc1-837fddad04b4.png)

Here are the subheader and subheader_labels layout files:

[gamespage_details_subheader.zip](https://github.com/Outsetini/Air-for-Steam/files/2326054/gamespage_details_subheader.zip)

**Comment by Outsetini** [comment] 2018-09-12 21:19
I'm actually not sure how to fix this. The subheader files don't reference anything particular that I can see, and I don't have a Linux box to test this out on either. :/

**Comment by AccountOneOff** [comment] 2018-09-12 23:39
Sorry I just checked through vgui and it's actually this file:

[gamespage_details_compat_subheader.zip](https://github.com/airforsteam/Air-for-Steam/files/2377145/gamespage_details_compat_subheader.zip)

**Comment by airforsteam** [comment] 2018-09-15 05:12
I'm actively working on getting this patched up (also a thread on the community group about it: https://steamcommunity.com/groups/airforsteam/discussions/1/3317353727665763102/).

Do you guys know if this adds any necessary functionality to Steam? Or is it a purely informational link?

**Comment by AccountOneOff** [comment] 2018-09-15 06:40
It's informational. It opens the settings window. 

![screenshot from 2018-09-14 23-38-55](https://user-images.githubusercontent.com/15083452/45583460-7ba79780-b877-11e8-8b6f-f0b3f8b90591.png)

**Comment by airforsteam** [comment] 2018-09-15 06:53
Do you think it's necessary to display the link on the game page?

**Comment by AccountOneOff** [comment] 2018-09-15 07:03
I do yes. It's not apparent what is or isn't a Windows only game now. It use to be we couldn't download them at all but now there's no difference and the dialog acts as a sort of warning that the game might not work.

**Comment by airforsteam** [comment] 2018-09-15 07:26
Can you check with the latest commit and see if it worked? A screenshot would be much appreciated (assuming the text actually appears where it should be). I'm attempting to center it under the Install button.

**Comment by Nik-mmzd** [comment] 2018-09-15 07:34
![image](https://user-images.githubusercontent.com/19509291/45583897-ec2fd200-b8d2-11e8-8cd0-1d71238fec9b.png)
A bit better

**Comment by airforsteam** [comment] 2018-09-15 07:42
Hah, I don't even know if I should pretend to be surprised - welcome to steam skinning. ;)

Can you give it another try now?

**Comment by airforsteam** [comment] 2018-09-15 07:43
I'm feeling a 50/50 chance that it'll be fully left-aligned this time...

**Comment by Nik-mmzd** [comment] 2018-09-15 07:44
You won, fully left-aligned
![image](https://user-images.githubusercontent.com/19509291/45583983-4e3d0700-b8d4-11e8-9176-c342d9221cb2.png)

**Comment by airforsteam** [comment] 2018-09-15 07:52
Drat. Okay, one more try at centering it with a bit of a hacky solution this time. If this doesn't work I'll probably just align it with the left column as the second best option.

**Comment by Nik-mmzd** [comment] 2018-09-15 07:54
![image](https://user-images.githubusercontent.com/19509291/45584053-9ad51200-b8d5-11e8-9852-bafdef318599.png)

**Comment by airforsteam** [comment] 2018-09-15 07:56
Gave it 10px more, hopefully that allows it to fit onto one line..

**Comment by Nik-mmzd** [comment] 2018-09-15 07:57
Nope
![image](https://user-images.githubusercontent.com/19509291/45584077-2cdd1a80-b8d6-11e8-90f3-65c55537d070.png)

**Comment by airforsteam** [comment] 2018-09-15 07:59
This is killing me haha, sorry. This time?

**Comment by Nik-mmzd** [comment] 2018-09-15 08:00
Yay, it's worked
![image](https://user-images.githubusercontent.com/19509291/45584094-76c60080-b8d6-11e8-8fa4-1238a129e148.png)

**Comment by airforsteam** [comment] 2018-09-15 08:00
Yesssss! You think that looks alright there?

**Comment by Nik-mmzd** [comment] 2018-09-15 08:05
Yep

**Comment by airforsteam** [comment] 2018-09-15 08:06
Excellent. Thanks a bunch for your help there, it was quite invaluable.

**Comment by AccountOneOff** [comment] 2018-09-15 21:18
Thanks for your work!

**Comment by airforsteam** [comment] 2018-09-16 18:07
Another Linux user is having trouble clicking links below the new compability text (eg. Support & DLC) - can someone verify whether or not this is an issue for everyone?

**Comment by Nik-mmzd** [comment] 2018-09-16 18:45
@airforsteam confirmed
Store Page, DLC, Support are not clickable

Also reviews button is covered by achievements
![image](https://user-images.githubusercontent.com/19509291/45599743-d0731b80-b9f9-11e8-851a-198432e58bd3.png)

"Set Categories" works well

**Comment by airforsteam** [comment] 2018-09-17 20:19
The cut off text is an issue with the font size rendering in Linux vs Windows - the best way to fix that is to adjust the global font sizes in resources\styles\_fonts.styles.

I also just pushed a change that *should* fix the non-clickable menus. Let me know if it works for you.

**Comment by Nik-mmzd** [comment] 2018-09-17 22:30
Menus are working

But I found a strange thing:
I clicked "Store Page", then clicked "Library" and got this glitch
https://imgur.com/a/MBXAU37
(I don't think it's a skin bug, but I see this thing first time)

**Comment by airforsteam** [comment] 2018-09-18 01:42
Whoa, yeah, that's not something I've ever seen on my end - it definitely shouldn't be related to the change I just made. Seems more likely that something odd happened within Steam. Unless it's consistent and fixes when you roll back to the last commit. I'm going to re-close this issue since the original topic has been fully addressed as of now.

**Closed by airforsteam** 2018-09-18 01:42 UTC
Labels: Linux, bug
